global using Moq;
global using Xunit;
global using AutoFixture;
global using IndependentReserve.DotNetClientApi;
global using IndependentReserve.DotNetClientApi.Data;
global using Trader.Domain.Enums;
global using Trader.Domain.OutboundPorts;
global using Trader.Adapter.IndependentReserve.Config;
global using Trader.Adapter.IndependentReserve.Repositories;